In [214]:
import numpy as np

In [215]:
x=[[20,25,30,35],
   [9,10,11,12],
   [4,2,3,1]]
   

In [227]:
def euc(x1,x2):
    my_s=0
    for i in range(len(x1)):
        my_s += (x1[i]-x2[i])**2
    return np.sqrt(my_s)

In [228]:
def p_f(x,sigma):
    p = np.ndarray((len(x),len(x)))
    for i in range(len(x)):
        my_sum = 0
        for k in range(len(x)):
            if i!=k:
                my_sum += (np.exp(-(((euc(x[i],x[k]))**2))/(2*sigma[i]**2)))
        for j in range(len(x)):
            if i!=j:
                p[i][j]=((np.exp(-((euc(x[i],x[j]))**2)/(2*sigma[i]**2)))/my_sum)
            else:
                p[i][j]=0
    for i in range(len(p)):
        for j in range(len(p)):
            if i >= j:
                continue
            p[i][j]=(p[i][j]+p[j][i])/2*len(x[0])
            p[j][i]=p[i][j]
    return p    

In [229]:
y=[[1,2,3],[90,78,60]]

In [230]:
def q(y):
    q=np.ndarray((len(y),len(y)))
    my_sum=0
    for k in range(len(y)):
        for l in range(len(y)):
            if k!=l:
                my_sum += 1/(1+(euc(y[k],y[l]))**2)
                print(my_sum)
    for i in range(len(y)):
        for j in range(len(y)):
            if i!=j:
                q[i][j]=(1/(1+(euc(y[i],y[j]))**2))/(my_sum)
            else:
                q[i][j]=0
    return q     

In [231]:
print(q(y))

5.9007493951731886e-05
0.00011801498790346377
[[0.  0.5]
 [0.5 0. ]]


In [232]:
print(p_f(x,[20,20,20]))

[[0.         2.17652858 0.38083752]
 [2.17652858 0.         3.44263391]
 [0.38083752 3.44263391 0.        ]]


In [224]:
def binary():
    pass

In [ ]:
def  sigma(i):
    pass

In [225]:
def main():
    pass

In [226]:
def descent():
    pass